apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: restored-mysql
  namespace: demo
spec:
  version: "8.0.14"
  databaseSecret:
    secretName: sample-mysql-auth
  replicas: 1
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    stashRestoreSession:
      name: restore-sample-mysql
  terminationPolicy: WipeOut